/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientDashboardRouteImport } from './routes/patient-dashboard'
import { Route as DoctorDashboardRouteImport } from './routes/doctor-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient-dashboard',
  path: '/patient-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor-dashboard',
  path: '/doctor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/patient-dashboard': typeof PatientDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/patient-dashboard': typeof PatientDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/patient-dashboard': typeof PatientDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doctor-dashboard' | '/patient-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctor-dashboard' | '/patient-dashboard'
  id: '__root__' | '/' | '/doctor-dashboard' | '/patient-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient-dashboard': {
      id: '/patient-dashboard'
      path: '/patient-dashboard'
      fullPath: '/patient-dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-dashboard': {
      id: '/doctor-dashboard'
      path: '/doctor-dashboard'
      fullPath: '/doctor-dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  PatientDashboardRoute: PatientDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
